### ISSUE TITLE
Login with E-Mail doesnt work

### ISSUE THREAD

**Issue by NatsuDragneelKl** [fumeapp/laranuxt#100]
Hey, I tried to login with Mail but this doesnt work.

I got the Mail but nothing happens after clicking this. 

No Errors, I'am still not logged in.

Any Idea?

Thanks for your work!

**Comment by tcampbPPU** [comment]
Thanks for letting us know, I will check it out.

**Comment by tcampbPPU** [comment]
Looks like its an issue with the global middle ware [auth.global.ts](https://github.com/fumeapp/laranuxt/blob/main/client/middleware/auth.global.ts) its probably applying to all pages, 
I think you can do something like this in the page setup:
```vue
<script lang="ts" setup>
definePageMeta({
  middleware: 'guest',
  title: 'Authenticating..',
})
</script>``

**Comment by acidjazz** [comment]
I think our last template update I might have messed with that middleware - ill fix it all up when we do the iconify -> icon module conversion

**Comment by NatsuDragneelKl** [comment]
I'am new to Nuxt3 but testing some stuff here, I don't understand where I have to place the script stuff to make login link work for me?

**Comment by tcampbPPU** [comment]
@NatsuDragneelKl Should be fixed now with latest PR #101

**Comment by NatsuDragneelKl** [comment]
yeah this works :) thanks!

**Comment by dany-eudes** [comment]
It looks like the error reported here is back. When clicking on the email link, the application returns error 500 and displays that the guest middleware does not exist. 
Placing a dummy `guest.ts` in `client/middleware` folder seems to solve the issue.

```
export default defineNuxtRouteMiddleware(() => {
  // example guest middleware
})

```
It's not a good solution, nor the most appropriate one, certainly.

**Comment by tcampbPPU** [comment]
Thanks for letting us know, I will check it out when I have some time.

**Comment by tcampbPPU** [comment]
@dany-eudes should be resolved now
