### ISSUE TITLE
nuxt v3 - auth module/plugin middleware

### ISSUE THREAD

**Issue by acidjazz** [fumeapp/laranuxt#54]
move `loggedIn` to a cookie check and stop there - properly respond to an access denied endpoint with removing the session and redirecting properly - keep the FE simple!

**Comment by dammy001** [comment]
@acidjazz has this been done now?

**Comment by acidjazz** [comment]
@dammy001 yes - i've actually found that by going after my API calls that require auth, any that respond with a 401 I use to redirect

Just remember to be careful when you do your calls so that when it does 401, you get no js errors so the redirect fires, example:

```ts
const { $api } = useNuxtApp()
const teams = ref<models.Teams|undefined>(undefined)
const get = async () => teams.value = (await $api.index<models.Teams>('/team'))?.data
get()
```

(notice the `?.data`)

**Comment by acidjazz** [comment]
@dammy001 i talk about this a bit more [here](https://github.com/nuxt/framework/discussions/2082#discussioncomment-1880342)

**Comment by dammy001** [comment]
Nice 👍
