### ISSUE TITLE
Static Analyser

### ISSUE THREAD

**Issue by dammy001** [fumeapp/laranuxt#62]
@acidjazz what's your take on adding phpstan?

**Comment by acidjazz** [comment]
@dammy001 Never used it! Be open to maybe a GitHub action of some sort?

**Comment by dammy001** [comment]
@acidjazz was actually referring to this https://github.com/nunomaduro/larastan

**Comment by acidjazz** [comment]
@dammy001 sounds awesome, hearing great things about it, maybe we can get a github action going that runs it against this codebase

**Comment by dammy001** [comment]
@acidjazz Yeah... Would love to join your organization to contribute more
