### ISSUE TITLE
Permission denied when trying to clone git repo

### ISSUE THREAD

**Issue by Arturexe** [fumeapp/laranuxt#94]
```
❯ git clone git@github.com:fumeapp/laranuxt.git
Cloning into 'laranuxt'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tcampbPPU** [comment]
Looks like your are cloning with `ssh`, when you go to your [GitHub settings](https://github.com/settings/keys) do you have a SSH registered?

**Comment by tcampbPPU** [comment]
> Looks like your are cloning with `ssh`, when you go to your [GitHub settings](https://github.com/settings/keys) do you have a SSH registered?

You can also try just cloning with regular `HTTPS`
```bash
git clone https://github.com/fumeapp/laranuxt.git
```

**Comment by Arturexe** [comment]
I had a `ssh` key in my settings but even after I deleted it, the problem persisted. Using `HTTPS` works though. Thank you.

**Comment by tcampbPPU** [comment]
> I had a `ssh` key in my settings but even after I deleted it, the problem persisted. Using `HTTPS` works though. Thank you.

Maybe create new ssh key and upload it your GitHub settings, this [link](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) might be able to help you out.
